sudo: false
language: node_js
node_js:
  - '12'
install:
  - npm install npm -g
  - npm run install-all
  - npm install -g pm2
before_install:
- openssl aes-256-cbc -K $encrypted_995f46ea43c0_key -iv $encrypted_995f46ea43c0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: npm run travis-deploy && pm2 kill
  on:
    branch: master
